# Generated by Django 4.1.13 on 2024-04-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_propertylistmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='people/images/')),
            ],
        ),
    ]
