# Generated by Django 4.1.13 on 2024-04-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_peoplemodel_options_peoplemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
