# Generated by Django 4.1.13 on 2024-04-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_propertylistmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistmodel',
            name='floor_size',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=548, null=True
            ),
        ),
        migrations.AddField(
            model_name='propertylistmodel',
            name='number_of_bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylistmodel',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylistmodel',
            name='psf',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=548, null=True
            ),
        ),
        migrations.AddField(
            model_name='propertylistmodel',
            name='type_of_property',
            field=models.CharField(
                choices=[
                    ('APARTMENT', 'Apartment'),
                    ('SHOP', 'Shop'),
                    ('OFFICE_SPACE', 'Office_Space'),
                    ('HOUSE', 'House'),
                ],
                default='APARTMENT',
                max_length=512,
            ),
        ),
    ]
