# Generated by Django 4.1.13 on 2024-04-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_propertylistmodel_floor_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylistmodel',
            name='number_of_bathrooms',
        ),
    ]
