# Generated by Django 4.1.13 on 2024-04-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_rename_number_of_rooms_propertylistmodel_number_of_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistmodel',
            name='type_of_property',
            field=models.CharField(
                choices=[
                    ('Apartment', 'Apartment'),
                    ('Shop', 'Shop'),
                    ('Office_Space', 'Office_Space'),
                    ('House', 'House'),
                ],
                default='Apartment',
                max_length=512,
            ),
        ),
        migrations.CreateModel(
            name='PropertyListImages',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(upload_to='property-list/carousel/images/'),
                ),
                (
                    'property',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='cms.propertylistmodel',
                    ),
                ),
            ],
        ),
    ]
