# Generated by Django 4.1.13 on 2024-04-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_alter_propertylistmodel_type_of_property_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertylistimages",
            options={"verbose_name_plural": "Carousel Images"},
        ),
        migrations.AddField(
            model_name="propertylistmodel",
            name="type_of_offer",
            field=models.CharField(
                choices=[("Sell", "Sell"), ("Rent", "Rent")],
                default="Rent",
                max_length=512,
            ),
        ),
    ]
