# Generated by Django 4.1.13 on 2024-04-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_alter_propertylistimages_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertylistmodel",
            name="type_of_offer",
            field=models.CharField(
                choices=[("Buy", "Buy"), ("Rent", "Rent")],
                default="Rent",
                max_length=512,
            ),
        ),
    ]
